server:
  port: 8010
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/ # file 경로 대신 classpath 사용
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/nine_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: # 비밀번호 입력이 필요한 경우 여기에 입력
  jpa:
    hibernate:
      ddl-auto: update
